const defineTemplate = (id, name, description, content) =>
  Object.freeze({ id, name, description, content });

export const ROUTINE_TEMPLATES = Object.freeze([
  defineTemplate(
    'standard-routine',
    'Standard Routine',
    'Standard INIT/PROCESS routine skeleton.',
    [
      'SUBROUTINE {{ROUTINE_NAME}}',
      '$INSERT I_COMMON',
      '$INSERT I_EQUATE',
      '{{LAYOUT_INSERTS}}',
      '* $INSERT I_ENQUIRY.COMMON',
      '',
      'GOSUB INIT',
      'GOSUB PROCESS',
      'RETURN',
      '',
      'INIT:',
      '{{INIT}}',
      'RETURN',
      '',
      'PROCESS:',
      '{{PROCESS}}',
      'RETURN',
      '',
      'END',
    ].join('\n'),
  ),
  defineTemplate(
    'ofs-routine',
    'OFS Routine',
    'OFS-oriented routine preset.',
    [
      'SUBROUTINE {{ROUTINE_NAME}}',
      '$INSERT I_COMMON',
      '$INSERT I_EQUATE',
      '{{LAYOUT_INSERTS}}',
      '',
      'GOSUB INIT',
      'GOSUB PROCESS',
      'RETURN',
      '',
      'INIT:',
      "    OFS.STRING = ''",
      "    OFS.RESPONSE = ''",
      'RETURN',
      '',
      'PROCESS:',
      '{{PROCESS}}',
      'RETURN',
      '',
      'END',
    ].join('\n'),
  ),
  defineTemplate(
    'ofs-opm',
    'OFS OPM Routine',
    'OFS operation-manager routine preset.',
    [
      'SUBROUTINE {{ROUTINE_NAME}}',
      '$INSERT I_COMMON',
      '$INSERT I_EQUATE',
      '{{LAYOUT_INSERTS}}',
      '',
      'GOSUB INIT',
      'GOSUB PROCESS',
      'RETURN',
      '',
      'INIT:',
      "    OPM.STATUS = ''",
      'RETURN',
      '',
      'PROCESS:',
      '{{PROCESS}}',
      'RETURN',
      '',
      'END',
    ].join('\n'),
  ),
  defineTemplate(
    'fwrite-routine',
    'F.WRITE Routine',
    'F.READ/F.WRITE preset with one consistent record variable.',
    [
      'SUBROUTINE {{ROUTINE_NAME}}',
      '$INSERT I_COMMON',
      '$INSERT I_EQUATE',
      '{{LAYOUT_INSERTS}}',
      '',
      'GOSUB INIT',
      'GOSUB PROCESS',
      'RETURN',
      '',
      'INIT:',
      '{{INIT}}',
      'RETURN',
      '',
      'PROCESS:',
      '    CALL F.READ(FN.FILE, ID, R.FILE, F.FILE, ERR)',
      '{{PROCESS}}',
      '    CALL F.WRITE(FN.FILE, ID, R.FILE, F.FILE)',
      'RETURN',
      '',
      'END',
    ].join('\n'),
  ),
]);

export const ROUTINE_TEMPLATES_BY_ID = Object.freeze(
  Object.fromEntries(ROUTINE_TEMPLATES.map((template) => [template.id, template])),
);

export function getRoutineTemplate(id) {
  return ROUTINE_TEMPLATES_BY_ID[id] || null;
}
