import React,{useEffect,useMemo,useState}from'react';
import{buildRepositoryIndex,attachFileHandles,buildContext,detectCycles,findDependencies,findDependents,getSymbolDetails,getArchitecture}from'../../services/repository';
import{searchCode,searchIndex,discoverApis,scanSecurity,detectProjectPackages,buildArchitectureMermaid}from'../../services/intelligence';

const cp=v=>v&&navigator.clipboard?.writeText(v);
const dl=(n,t)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};

export default function CodebasePanel({project,onOpenFile}){
 const[index,setIndex]=useState(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[view,setView]=useState('overview'),[selected,setSelected]=useState(new Set()),[selectedSymbol,setSelectedSymbol]=useState(null),[selectedFile,setSelectedFile]=useState(''),[context,setContext]=useState(''),[contextTokens,setContextTokens]=useState(0),[contextFiles,setContextFiles]=useState(0),[metadata,setMetadata]=useState(true),[includeDeps,setIncludeDeps]=useState(true),[includeDependents,setIncludeDependents]=useState(false),[error,setError]=useState('');
 const[searchResults,setSearchResults]=useState([]),[searchBusy,setSearchBusy]=useState(false),[regex,setRegex]=useState(false),[api,setApi]=useState([]),[security,setSecurity]=useState([]),[packages,setPackages]=useState([]),[diagram,setDiagram]=useState(''),[detailBusy,setDetailBusy]=useState(false);

 async function indexProject(){if(!project)return;setBusy(true);setError('');try{const next=attachFileHandles(await buildRepositoryIndex(project),project);next.project.packages=await detectProjectPackages(next);setIndex(next);setPackages(next.project.packages);setSelected(new Set(next.files.slice(0,25).map(f=>f.path)));setContext('');setSelectedSymbol(null)}catch(e){setError(e?.message||'Unable to index repository')}finally{setBusy(false)}}
 useEffect(()=>{if(!index)return;setPackages(index.project?.packages||[]);setDiagram(buildArchitectureMermaid(index))},[index]);
 const files=useMemo(()=> (index?.files||[]).filter(f=>!query||f.path.toLowerCase().includes(query.toLowerCase())||f.language.toLowerCase().includes(query.toLowerCase())),[index,query]);
 const symbols=useMemo(()=> (index?.symbols||[]).filter(s=>!query||s.name.toLowerCase().includes(query.toLowerCase())||s.path.toLowerCase().includes(query.toLowerCase())),[index,query]);
 const architecture=useMemo(()=>getArchitecture(index),[index]),cycles=useMemo(()=>detectCycles(index),[index]),details=useMemo(()=>getSymbolDetails(index,selectedSymbol),[index,selectedSymbol]);
 const profile=useMemo(()=>({frameworks:index?.project?.frameworks||[],languages:Object.entries(index?.languages||{}).sort((a,b)=>b[1]-a[1])}),[index]);

 async function runSearch(){if(!index||!query.trim())return;setSearchBusy(true);try{const indexed=searchIndex(index,query);const code=await searchCode(index,query,{regex});setSearchResults({indexed,code})}catch(e){setError(e.message)}finally{setSearchBusy(false)}}
 async function runAnalyzer(type){if(!index)return;setDetailBusy(true);try{if(type==='api')setApi(await discoverApis(index));if(type==='security')setSecurity(await scanSecurity(index));if(type==='diagram')setDiagram(buildArchitectureMermaid(index,{limit:150}))}catch(e){setError(e.message)}finally{setDetailBusy(false)}}
 function toggle(path){setSelected(s=>{const n=new Set(s);n.has(path)?n.delete(path):n.add(path);return n})}
 async function generateContext(){if(!index)return;setBusy(true);try{const r=await buildContext(index,[...selected],{includeMetadata:metadata,includeDependencies:includeDeps,includeDependents});setContext(r.content);setContextTokens(r.tokens);setContextFiles(r.files.length)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function selectAll(){setSelected(new Set((index?.files||[]).map(f=>f.path)))}
 if(!project)return <section><div className="empty">📂 Open a local folder first to build its codebase index.</div></section>;
 return <section className="codebase-intelligence">
  <div className="head"><div><h1>🧠 Codebase Intelligence</h1><small>Local repository intelligence: symbols, search, architecture, APIs, security and AI-ready context.</small></div><button onClick={indexProject}disabled={busy}>{busy?'⏳ Indexing...':'⚙ Build / Refresh Index'}</button></div>
  {error&&<div className="error">{error}</div>}
  {!index?<div className="panel"><h2>Repository Intelligence</h2><p className="muted">Build one local index. Source stays in your browser.</p><button onClick={indexProject}>🚀 Build Project Index</button></div>:<>
   <div className="cards intelligence-cards"><article><b>{index.stats.files}</b><span>Files</span></article><article><b>{index.stats.symbols}</b><span>Symbols</span></article><article><b>{index.stats.references}</b><span>References</span></article><article><b>{index.stats.resolvedReferences}</b><span>Resolved</span></article><article><b>{index.stats.internalEdges}</b><span>Internal edges</span></article><article><b>{security.length}</b><span>Security findings</span></article></div>
   <div className="tabs">{[['overview','Overview'],['search','Search'],['symbols','Symbols'],['architecture','Architecture'],['impact','Impact'],['api','API Discovery'],['security','Security'],['diagram','Diagram'],['context','Context Builder']].map(([k,l])=><button key={k}className={view===k?'active':''}onClick={()=>setView(k)}>{l}</button>)}</div>
   {['overview','files','symbols','architecture','impact'].includes(view)&&<div className="search"><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Filter files, symbols or dependencies"/><button onClick={()=>setQuery('')}>✕ Clear</button></div>}
   {view==='overview'&&<div className="analyze-grid"><div className="analytics-panel"><h2>Project Profile</h2>{profile.frameworks.map(x=><div className="index-row"key={x.name}><b>{x.name}</b><span>detected</span><small>{x.evidence}</small></div>)}{packages.slice(0,20).map(x=><div className="index-row"key={x.package}><b>{x.package}</b><span>{x.version}</span><small>{x.category}</small></div>)}{profile.languages.map(([l,c])=><div className="index-row"key={l}><b>{l}</b><span>{c} files</span><small>{Math.round(c/index.stats.files*100)}%</small></div>)}</div><div className="analytics-panel"><h2>Health Signals</h2><Metric label="Unresolved relative imports" value={index.unresolvedImports.length}/><Metric label="Circular dependency paths" value={cycles.length}/><Metric label="Unresolved references" value={index.stats.unresolvedReferences}/><Metric label="Parser errors" value={index.files.reduce((s,f)=>s+(f.parseErrors?.length||0),0)}/><Metric label="External imports" value={index.externalDependencies.length}/><Metric label="Security findings" value={security.length}/></div></div>}
   {view==='search'&&<div className="analytics-panel"><div className="transform-toolbar"><b>🔎 Indexed + Full-text Search</b><label><input type="checkbox"checked={regex}onChange={e=>setRegex(e.target.checked)}/> Regex</label><button onClick={runSearch}disabled={searchBusy}>{searchBusy?'⏳ Searching...':'▶ Search'}</button></div><div className="search"><input autoFocus value={query}onChange={e=>setQuery(e.target.value)}onKeyDown={e=>e.key==='Enter'&&runSearch()}placeholder="Search symbols, files and source text"/><button onClick={()=>{setQuery('');setSearchResults([])}}>✕ Clear</button></div>{searchResults?.indexed?.map((r,i)=><button className="index-row clickable"key={'i'+i}onClick={()=>setSelectedFile(r.path)}><b>{r.label}</b><span>{r.type}</span><small>{r.path}{r.line?':'+r.line:''} · {r.detail}</small></button>)}{searchResults?.code?.map((r,i)=><button className="index-row clickable"key={'c'+i}onClick={()=>{setSelectedFile(r.path);onOpenFile?.(project.files.find(f=>f.path===r.path),true)}}><b>{r.path}:{r.line}</b><span>{r.language}</span><small>{r.text}</small></button>)}{searchResults&&!searchResults.indexed?.length&&!searchResults.code?.length&&<p className="muted">No results.</p>}</div>}
   {view==='symbols'&&<div className="analytics-panel"><h2>Symbol Intelligence</h2>{symbols.slice(0,500).map(s=><button className="index-row clickable"key={s.definitionKey}onClick={()=>setSelectedSymbol(s.definitionKey)}><b>{s.name}</b><span>{s.kind}{s.parent?' · '+s.parent:''}</span><small>{s.path}:{s.line}</small></button>)}{details&&<SymbolDetails details={details}onClose={()=>setSelectedSymbol(null)}/>}</div>}
   {view==='architecture'&&<div className="analyze-grid"><div className="analytics-panel"><h2>Architecture Hotspots</h2>{architecture.slice(0,100).map(x=><button className="index-row clickable"key={x.path}onClick={()=>{setSelectedFile(x.path);setView('impact')}}><b>{x.path}</b><span>{x.dependencies} out · {x.dependents} in</span><small>{x.symbols} symbols · ~{x.tokens.toLocaleString()} tokens</small></button>)}</div><div className="analytics-panel"><h2>Cycles</h2>{cycles.map((c,i)=><div className="cycle-row"key={i}>{c.join(' → ')}</div>)}{!cycles.length&&<p className="muted">No circular dependency paths detected.</p>}</div></div>}
   {view==='impact'&&<div className="analyze-grid"><div className="analytics-panel"><h2>File Impact</h2><select value={selectedFile}onChange={e=>setSelectedFile(e.target.value)}><option value="">Select a file</option>{index.files.map(f=><option key={f.path}>{f.path}</option>)}</select>{selectedFile&&<><h3>Dependencies</h3>{findDependencies(index,selectedFile).map(p=><div className="index-row"key={p}><b>{p}</b><span>outgoing</span></div>)}<h3>Imported by</h3>{findDependents(index,selectedFile).map(p=><div className="index-row"key={p}><b>{p}</b><span>incoming</span></div>)}</>}</div><div className="analytics-panel"><h2>Symbols</h2>{selectedFile?index.symbols.filter(s=>s.path===selectedFile).map(s=><button className="index-row clickable"key={s.definitionKey}onClick={()=>{setSelectedSymbol(s.definitionKey);setView('symbols')}}><b>{s.name}</b><span>{s.references.length} refs</span><small>{s.importedBy.length} importers</small></button>):<p className="muted">Select a file.</p>}</div></div>}
   {view==='api'&&<AnalyzerView title="🌐 API / Route Discovery"items={api}empty="Run discovery to find route/controller declarations."busy={detailBusy}onRun={()=>runAnalyzer('api')}columns={['method','path','framework','file','line']}/>}
   {view==='security'&&<AnalyzerView title="🔐 Security / Secret Scan"items={security}empty="Run a local heuristic scan for likely secrets and credentials."busy={detailBusy}onRun={()=>runAnalyzer('security')}columns={['severity','id','path','line','text']}/>}
   {view==='diagram'&&<div className="analytics-panel"><div className="transform-toolbar"><b>🏗️ Architecture Diagram</b><span className="muted">Mermaid source</span><button onClick={()=>runAnalyzer('diagram')}>{detailBusy?'⏳':'▶ Generate'}</button><button onClick={()=>cp(diagram)}>📋 Copy</button><button onClick={()=>dl((project.name||'repository')+'-architecture.mmd',diagram)}>⬇ Download</button></div><textarea className="diagram-output"value={diagram}onChange={e=>setDiagram(e.target.value)}/><div className="diagram-preview"><pre>{diagram}</pre></div><p className="muted">Paste the Mermaid source into RepoMind Markdown Viewer or any Mermaid-compatible renderer.</p></div>}
   {view==='context'&&<div className="context-builder"><div className="panel"><div className="transform-toolbar"><b>AI Context Builder</b><span className="muted">{selected.size} selected</span><button onClick={selectAll}>☑ Select All</button><button onClick={()=>setSelected(new Set())}>☐ Clear</button></div><div className="search"><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Filter files"/><button onClick={()=>setQuery('')}>✕ Clear</button></div><div className="file-checks">{files.map(f=><label key={f.path}><input type="checkbox"checked={selected.has(f.path)}onChange={()=>toggle(f.path)}/>{f.path}</label>)}</div><label className="context-option"><input type="checkbox"checked={metadata}onChange={e=>setMetadata(e.target.checked)}/> Include file metadata</label><label className="context-option"><input type="checkbox"checked={includeDeps}onChange={e=>setIncludeDeps(e.target.checked)}/> Include direct dependencies</label><label className="context-option"><input type="checkbox"checked={includeDependents}onChange={e=>setIncludeDependents(e.target.checked)}/> Include direct importers</label><div className="tool-run-strip"><button onClick={generateContext}disabled={!selected.size||busy}>{busy?'⏳ Generating...':'▶ Generate Context'}</button><button onClick={()=>cp(context)}disabled={!context}>📋 Copy</button><button onClick={()=>dl((project.name||'repository')+'-context.md',context)}disabled={!context}>⬇ Download</button></div></div><div className="panel"><div className="transform-toolbar"><b>Generated Context</b><span>~{contextTokens.toLocaleString()} tokens · {contextFiles} files</span></div><textarea className="context-output"value={context}readOnly/></div></div>}
  </>}
 </section>;
}
function Metric({label,value}){return <div className="index-row"><b>{label}</b><span>{value}</span><small>{value?'Review':'None detected'}</small></div>}
function AnalyzerView({title,items,empty,busy,onRun,columns}){return <div className="analytics-panel"><div className="transform-toolbar"><b>{title}</b><span>{items.length} findings</span><button onClick={onRun}disabled={busy}>{busy?'⏳ Scanning...':'▶ Run Scan'}</button></div>{items.map((x,i)=><div className="index-row analyzer-row"key={i}>{columns.map(c=><span key={c}title={String(x[c]??'')}>{String(x[c]??'')}</span>)}</div>)}{!items.length&&<p className="muted">{empty}</p>}</div>}
function SymbolDetails({details,onClose}){const{symbol}=details;return <div className="symbol-inspector panel"><div className="transform-toolbar"><div><b>{symbol.name}</b><span className="muted"> · {symbol.kind} · {symbol.path}:{symbol.line}</span></div><button onClick={onClose}>✕ Close</button></div><div className="analyze-grid"><div><h3>Definition</h3><p className="muted">{symbol.path}:{symbol.line}:{symbol.column}</p><h3>Methods</h3>{details.methods.length?details.methods.map(x=><div className="mini-row"key={x.definitionKey}>{x.name}()</div>):<p className="muted">No class methods.</p>}</div><div><h3>References ({details.references.length})</h3>{details.references.slice(0,100).map((r,i)=><div className="mini-row"key={i}>{r.from}:{r.line}:{r.column}</div>)}</div></div><h3>Imported by ({details.importedBy.length})</h3>{details.importedBy.map((x,i)=><div className="index-row"key={i}><b>{x.from}</b><span>{x.local}</span><small>{x.imported} · line {x.line}</small></div>)}</div>}
