import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const EXTS=new Set(['.js','.jsx','.ts','.tsx','.vue','.py','.java','.kt','.go','.rs','.php','.cs','.cpp','.c','.h','.html','.css','.scss','.json','.md','.txt','.xml','.yaml','.yml','.sql','.sh','.bat','.ps1','.env']);const IGN=new Set(['.git','node_modules','dist','build','.venv','venv','__pycache__','.idea','.vscode']);
async function walk(h,p='',a=[]){for await(const[n,x]of h.entries())if(x.kind==='directory'){if(!IGN.has(n))await walk(x,p?p+'/'+n:n,a)}else{let e='.'+(n.split('.').pop()||'').toLowerCase();a.push({name:n,path:p?p+'/'+n:n,ext:e,text:EXTS.has(e)||['Dockerfile','Makefile','.gitignore'].includes(n),handle:x})}return a}
const read=async f=>(await f.handle.getFile()).text();const esc=s=>s.replace(/[.*+?^()|[\]\\]/g,'\\$&');const dl=(n,t)=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t]));a.download=n;a.click()};const cp=t=>navigator.clipboard?.writeText(t);
function App(){const[d,setD]=useState(),[p,setP]=useState(),[sel,setSel]=useState(),[tab,setTab]=useState('overview'),[q,setQ]=useState(''),[res,setRes]=useState([]),[text,setText]=useState(''),[dirty,setDirty]=useState(false),[tools,setTools]=useState('json'),[tin,setTin]=useState(''),[regex,setRegex]=useState(''),[regexText,setRegexText]=useState(''),[tout,setTout]=useState(''),[diff,setDiff]=useState(),[compiled,setCompiled]=useState(''),[split,setSplit]=useState(''),[parts,setParts]=useState([]),[err,setErr]=useState('');
async function folder(){try{let h=await showDirectoryPicker({mode:'readwrite'}),fs=await walk(h),ex={};fs.forEach(f=>ex[f.ext]=(ex[f.ext]||0)+1);setD(h);setP({name:h.name,files:fs,stats:{files:fs.length,ext:ex,bytes:0}});setTab('overview');setErr('')}catch(e){if(e.name!=='AbortError')setErr(e.message)}}
async function open(f){if(!f.text)return setErr('Binary or unsupported file');try{let c=await read(f);setSel({...f,content:c});setText(c);setDirty(false);setTab('editor')}catch(e){setErr(e.message)}}
async function save(){try{let w=await sel.handle.createWritable();await w.write(text);await w.close();setDirty(false);setSel({...sel,content:text})}catch(e){setErr(e.message)}}
async function search(){if(!p||!q)return;let a=[];let re;try{re=new RegExp(esc(q),'i')}catch{return}for(let f of p.files.filter(x=>x.text)){let c=await read(f);c.split(/\r?\n/).forEach((l,i)=>{if(re.test(l))a.push({path:f.path,line:i+1,text:l})})}setRes(a);setTab('search')}
async function combine(){let a=[];for(let f of p.files.filter(x=>x.text))a.push('/* --- Start of file: '+f.path+' --- */\n'+await read(f)+'\n/* --- End of file: '+f.path+' --- */');setCompiled(a.join('\n\n'));setTab('transform')}
function dosplit(){let r=/\/\* --- Start of file: (.*?) --- \*\/\n([\\s\\S]*?)\n\/\* --- End of file: \\1 --- \*\//g,m,a=[];while(m=r.exec(split))a.push({name:m[1],content:m[2]});setParts(a)}
function runTool(){try{let o='';if(tools==='json')o=JSON.stringify(JSON.parse(tin),null,2);else if(tools==='text')o=tin.replace(/[ \t]+/g,' ').split(/\r?\n/).map(x=>x.trim()).filter((x,i,a)=>x!==''||i===0||a[i-1]!=='').join('\n').trim();else if(tools==='base64')o=btoa(unescape(encodeURIComponent(tin)));else if(tools==='uuid')o=crypto.randomUUID();else if(tools==='timestamp')o=tin?new Date(Number(tin)*1000).toISOString():String(Math.floor(Date.now()/1000));else if(tools==='jwt'){let x=tin.split('.')[1];o=JSON.stringify(JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,'+').replace(/_/g,'/'))))),null,2)}else if(tools==='regex'){let r=new RegExp(regex,'g');let matches=[...regexText.matchAll(r)].map(x=>({match:x[0],index:x.index,line:regexText.slice(0,x.index).split(/\r?\n/).length}));o=JSON.stringify({count:matches.length,matches},null,2)}setTout(o)}catch(e){setTout('Error: '+e.message)}}
return <><header><div><b>RepoMind</b><small>Local-first codebase intelligence workspace</small></div><button onClick={folder}>Open Folder</button></header><div className="status">{p?<><b>{p.name}</b><span>{p.files.length} files</span><span>✓ Files stay in your browser</span></>:<span>Select a local folder to begin</span>}</div>{err&&<div className="error">{err}</div>}<nav>{['overview','explorer','search','editor','tools','diff','transform'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><main>
{tab==='overview'&&<Overview p={p}/>}
{tab==='explorer'&&<section><h1>Explorer</h1><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Filter files"/><div className="list">{p?.files.filter(f=>f.path.toLowerCase().includes(q.toLowerCase())).map(f=><button onClick={()=>open(f)}><span>{f.path}</span><small>{f.ext}</small></button>)}</div></section>}
{tab==='search'&&<section><h1>Search</h1><div className="search"><input value={q}onChange={e=>setQ(e.target.value)}onKeyDown={e=>e.key==='Enter'&&search()}placeholder="Find text"/><button onClick={search}>Search</button></div><div className="list">{res.map(r=><button onClick={()=>open(p.files.find(f=>f.path===r.path))}><b>{r.path} · Line {r.line}</b><code>{r.text}</code></button>)}</div></section>}
{tab==='editor'&&<Editor sel={sel}text={text}setText={x=>{setText(x);setDirty(true)}}dirty={dirty}save={save}/>}
{tab==='tools'&&<Tools tool={tools}setTool={setTools}input={tin}setInput={setTin}regex={regex}setRegex={setRegex}regexText={regexText}setRegexText={setRegexText}output={tout}run={runTool}clear={()=>{setTin('');setRegex('');setRegexText('');setTout('')}}/>}
{tab==='diff'&&<Diff p={p}setDiff={setDiff}diff={diff}/>}
{tab==='transform'&&<Transform p={p}combine={combine}compiled={compiled}setCompiled={setCompiled}split={split}setSplit={setSplit}parts={parts}dosplit={dosplit}/>}
</main><footer>© {new Date().getFullYear()} ZainKamali – RepoMind 🧠</footer></>}
function Overview({p}){if(!p)return <section className="hero"><h1>Analyze your codebase without uploading it</h1><p>RepoMind now works like MDFV, LineFind and ReCodeX: open the website, choose a folder, and work directly with local files.</p><div className="grid">{['Built-in Editor','Find & Replace foundation','Developer Tools Hub','Project Intelligence','Diff & Compare','ReCodeX Transform'].map(x=><article><b>{x}</b><span>Built into one local-first workspace.</span></article>)}</div></section>;return <section><h1>{p.name}</h1><div className="cards"><article><b>{p.files.length}</b><span>Files</span></article><article><b>{Object.keys(p.stats.ext).length}</b><span>File types</span></article><article><b>Local</b><span>No upload</span></article></div><h2>File types</h2>{Object.entries(p.stats.ext).sort((a,b)=>b[1]-a[1]).slice(0,15).map(x=><div className="bar"><span>{x[0]}</span><i><b style={{width:Math.max(4,x[1]/p.files.length*100)+'%'}}/></i><strong>{x[1]}</strong></div>)}</section>}
function Editor({sel,text,setText,dirty,save}){const[find,setFind]=useState(''),[rep,setRep]=useState('');if(!sel)return <section><h1>Editor</h1><p>Select a file from Explorer or Search.</p></section>;function replaceOne(){if(!find)return;let i=text.indexOf(find);if(i>=0)setText(text.slice(0,i)+rep+text.slice(i+find.length))}function replaceAll(){if(!find)return;setText(text.split(find).join(rep))}return <section><div className="head"><div><h1>{sel.path} {dirty&&<em>● modified</em>}</h1><small>Local editor with Find, Replace and Replace All.</small></div><button onClick={save}disabled={!dirty}>Save</button></div><div className="replace"><input value={find}onChange={e=>setFind(e.target.value)}placeholder="Find"/><input value={rep}onChange={e=>setRep(e.target.value)}placeholder="Replace with"/><button onClick={replaceOne}>Replace</button><button onClick={replaceAll}>Replace All</button></div><div className="editor"><pre>{text.split(/\r?\n/).map((_,i)=><div>{i+1}</div>)}</pre><textarea spellCheck="false"value={text}onChange={e=>setText(e.target.value)}/></div></section>}
function Tools({tool,setTool,input,setInput,regex,setRegex,regexText,setRegexText,output,run,clear}){let ts=['text','json','base64','regex','jwt','uuid','timestamp'];return <section><div className="head"><div><h1>Developer Tools Hub</h1><p>Small developer utilities in one place.</p></div><button onClick={clear}>Clear</button></div><div className="tabs">{ts.map(x=><button className={tool===x?'active':''}onClick={()=>setTool(x)}>{x}</button>)}</div>{tool==='regex'?<div className="tool-grid"><div><label>Regular Expression</label><input value={regex}onChange={e=>setRegex(e.target.value)}placeholder="\\b[A-Z][a-z]+\\b"/><label>Test Text</label><textarea value={regexText}onChange={e=>setRegexText(e.target.value)}placeholder={"Hello RepoMind.\nThis Tool Finds Words."}/></div><div><button onClick={run}>Test Regex</button><textarea value={output}readOnly placeholder="Matches and results"/></div></div>:<><textarea value={input}onChange={e=>setInput(e.target.value)}placeholder={tool==='text'?'Paste text to clean...':'Input'}/><button onClick={run}>Run</button><textarea value={output}readOnly placeholder="Output"/></>}</section>}
function Diff({p,diff,setDiff}){const[a,setA]=useState(''),[b,setB]=useState('');async function go(){let f=p.files.find(x=>x.path===a),g=p.files.find(x=>x.path===b);setDiff({a,b,x:await read(f),y:await read(g)})}return <section><h1>Diff & Compare</h1><div className="search"><select onChange={e=>setA(e.target.value)}><option>Select first</option>{p?.files.filter(f=>f.text).map(f=><option>{f.path}</option>)}</select><select onChange={e=>setB(e.target.value)}><option>Select second</option>{p?.files.filter(f=>f.text).map(f=><option>{f.path}</option>)}</select><button onClick={go}>Compare</button></div>{diff&&<div className="diff"><pre>{diff.x}</pre><pre>{diff.y}</pre></div>}</section>}
function Transform({p,combine,compiled,setCompiled,split,setSplit,parts,dosplit}){return <section><h1>Transform</h1><div className="panel"><button onClick={combine}>Combine all text files</button><textarea value={compiled}onChange={e=>setCompiled(e.target.value)}/><button onClick={()=>dl('compiled_output.txt',compiled)}>Download</button></div><div className="panel"><h2>Reverse Split</h2><textarea value={split}onChange={e=>setSplit(e.target.value)}/><button onClick={dosplit}>Split</button>{parts.map(x=><p><b>{x.name}</b></p>)}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);