import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{marked}from'marked';
import DOMPurify from'dompurify';
import'./styles.css';
const EXTS=new Set(['.js','.jsx','.ts','.tsx','.vue','.py','.java','.kt','.go','.rs','.php','.cs','.cpp','.c','.h','.html','.css','.scss','.json','.md','.txt','.xml','.yaml','.yml','.sql','.sh','.bat','.ps1','.env']);const IGN=new Set(['.git','node_modules','dist','build','.venv','venv','__pycache__','.idea','.vscode']);
const read=async f=>(await f.handle.getFile()).text();const esc=s=>s.replace(/[.*+?^()|[\\]\\]/g,'\\\\$&');const dl=(n,t)=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};const cp=t=>navigator.clipboard?.writeText(t);const highlight=(line,term)=>{if(!term)return line;let parts=line.split(new RegExp('('+esc(term)+')','ig'));return parts.map((x,i)=>i%2?<mark key={i}>{x}</mark>:x)};
async function walk(h,p='',a=[]){for await(const[n,x]of h.entries())if(x.kind==='directory'){if(!IGN.has(n))await walk(x,p?p+'/'+n:n,a)}else{let e='.'+(n.split('.').pop()||'').toLowerCase();a.push({name:n,path:p?p+'/'+n:n,ext:e,text:EXTS.has(e)||['Dockerfile','Makefile','.gitignore'].includes(n),handle:x})}return a}
function App(){const[d,setD]=useState(),[p,setP]=useState(),[sel,setSel]=useState(),[tab,setTab]=useState('overview'),[q,setQ]=useState(''),[res,setRes]=useState([]),[text,setText]=useState(''),[dirty,setDirty]=useState(false),[tools,setTools]=useState('json'),[tin,setTin]=useState(''),[regex,setRegex]=useState(''),[regexText,setRegexText]=useState(''),[tout,setTout]=useState(''),[diff,setDiff]=useState(),[compiled,setCompiled]=useState(''),[split,setSplit]=useState(''),[parts,setParts]=useState([]),[err,setErr]=useState(''),[searchView,setSearchView]=useState(null),[showFind,setShowFind]=useState(true);
async function folder(){try{let h=await showDirectoryPicker({mode:'readwrite'}),fs=await walk(h),ex={};fs.forEach(f=>ex[f.ext]=(ex[f.ext]||0)+1);setD(h);setP({name:h.name,files:fs,stats:{files:fs.length,ext:ex,bytes:0}});setSel(null);setSearchView(null);setTab('overview');setErr('')}catch(e){if(e.name!=='AbortError')setErr(e.message)}}
async function open(f,fromSearch=false){if(!f?.text)return setErr('Binary or unsupported file');try{let c=await read(f);setSel({...f,content:c});setText(c);setDirty(false);setErr('');if(fromSearch){setSearchView({file:{...f,content:c},query:q});setTab('search')}else setTab('editor')}catch(e){setErr(e.message)}}
async function save(){try{let w=await sel.handle.createWritable();await w.write(text);await w.close();setDirty(false);setSel({...sel,content:text});if(searchView?.file?.path===sel.path)setSearchView({...searchView,file:{...sel,content:text}})}catch(e){setErr(e.message)}}
async function search(){if(!p||!q.trim())return;let a=[];for(let f of p.files.filter(x=>x.text)){let c=await read(f);c.split(/\r?\n/).forEach((l,i)=>{if(new RegExp(esc(q),'i').test(l))a.push({path:f.path,line:i+1,text:l})})}setRes(a);setSearchView(null);setTab('search')}
async function combine(){let a=[];for(let f of p.files.filter(x=>x.text))a.push('/* --- Start of file: '+f.path+' --- */\n'+await read(f)+'\n/* --- End of file: '+f.path+' --- */');setCompiled(a.join('\n\n'));setTab('transform')}
function dosplit(){let r=/\/\* --- Start of file: (.*?) --- \*\/\n([\s\S]*?)\n\/\* --- End of file: \1 --- \*\//g,m,a=[];while(m=r.exec(split))a.push({name:m[1],content:m[2]});setParts(a)}
function runTool(){try{let o='';if(tools==='json')o=JSON.stringify(JSON.parse(tin),null,2);else if(tools==='text')o=tin.replace(/[ \t]+/g,' ').split(/\r?\n/).map(x=>x.trim()).filter((x,i,a)=>x!==''||i===0||a[i-1]!=='').join('\n').trim();else if(tools==='base64')o=btoa(unescape(encodeURIComponent(tin)));else if(tools==='uuid')o=crypto.randomUUID();else if(tools==='timestamp')o=tin?new Date(Number(tin)*1000).toISOString():String(Math.floor(Date.now()/1000));else if(tools==='jwt'){let x=tin.split('.')[1];o=JSON.stringify(JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,'+').replace(/_/g,'/'))))),null,2)}else if(tools==='regex'){let r=new RegExp(regex,'g'),matches=[...regexText.matchAll(r)].map(x=>({match:x[0],index:x.index,line:regexText.slice(0,x.index).split(/\r?\n/).length}));o=JSON.stringify({count:matches.length,matches},null,2)}setTout(o)}catch(e){setTout('Error: '+e.message)}}
function clearTools(){setTin('');setRegex('');setRegexText('');setTout('')}
return <><header><div><b>RepoMind</b><small>Local-first codebase intelligence workspace</small></div><button onClick={folder}>📂 Open Folder</button></header><div className="status">{p?<><b>{p.name}</b><span>{p.files.length} files</span><span>✓ Files stay in your browser</span></>:<span>Select a local folder to begin</span>}</div>{err&&<div className="error">{err}</div>}<nav>{['overview','explorer','search','editor','tools','diff','transform'].map(x=><button key={x}className={tab===x?'active':''}onClick={()=>setTab(x)}>{x}</button>)}</nav><main>
{tab==='overview'&&<Overview p={p}/>}
{tab==='explorer'&&<section><h1>Explorer</h1><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Filter files"/><div className="list">{p?.files.filter(f=>f.path.toLowerCase().includes(q.toLowerCase())).map(f=><button key={f.path}onClick={()=>open(f)}><span>📄 {f.path}</span><small>{f.ext}</small></button>)}</div></section>}
{tab==='search'&&<SearchPanel p={p}q={q}setQ={setQ}search={search}res={res}open={open}searchView={searchView}setSearchView={setSearchView}setSel={setSel}setText={setText}setDirty={setDirty}showFind={showFind}setShowFind={setShowFind}/>}
{tab==='editor'&&<Editor sel={sel}text={text}setText={x=>{setText(x);setDirty(true)}}dirty={dirty}save={save}showFind={showFind}setShowFind={setShowFind}/>}
{tab==='tools'&&<Tools tool={tools}setTool={setTools}input={tin}setInput={setTin}regex={regex}setRegex={setRegex}regexText={regexText}setRegexText={setRegexText}output={tout}run={runTool}clear={clearTools}/>}
{tab==='diff'&&<Diff p={p}setDiff={setDiff}diff={diff}/>}
{tab==='transform'&&<Transform p={p}combine={combine}compiled={compiled}setCompiled={setCompiled}split={split}setSplit={setSplit}parts={parts}dosplit={dosplit}/>}
</main><footer>© {new Date().getFullYear()} ZainKamali – Repomind 🧠</footer></>}
function Overview({p}){const features=[['📂','Local Folder','Open a folder directly in the browser.'],['🗂️','Explorer','Browse the complete project file tree.'],['🔎','Search + Highlight','Find text, line numbers, highlights and navigation.'],['📝','Editor','Edit, find/replace, save, copy and download files.'],['📖','Markdown Viewer','Render Markdown with a clean document-style viewer.'],['🧰','Developer Tools','JSON, text cleanup, Base64, Regex, JWT, UUID and timestamps.'],['🔀','Diff & Compare','Compare two local files side by side.'],['🧩','Transform','Combine files and reverse-split ReCodeX-style output.'],['🔒','Local-first','Files stay on your machine; RepoMind does not upload them.']];return <section className="hero"><div className="hero-badge">🧠 Local Codebase Workspace</div><h1>{p?'Welcome to '+p.name:'Understand and work with your codebase locally'}</h1><p>{p?'Your project is open locally. Use the workspace below to explore, search, edit, inspect, transform and document it.':'Open a folder and use one workspace for code exploration, search, editing, Markdown, developer utilities, comparison and transformation.'}</p><div className="feature-grid">{features.map(([i,t,d])=><article key={t}><div className="feature-icon">{i}</div><div><b>{t}</b><span>{d}</span></div></article>)}</div>{p&&<><div className="cards"><article><b>{p.files.length}</b><span>Files</span></article><article><b>{Object.keys(p.stats.ext).length}</b><span>File types</span></article><article><b>Local</b><span>No upload</span></article></div><h2>File types</h2>{Object.entries(p.stats.ext).sort((a,b)=>b[1]-a[1]).slice(0,15).map(x=><div className="bar"key={x[0]}><span>{x[0]}</span><i><b style={{width:Math.max(4,x[1]/p.files.length*100)+'%'}}/></i><strong>{x[1]}</strong></div>)}</>}</section>}
function SearchPanel({p,q,setQ,search,res,open,searchView,setSearchView,setSel,setText,setDirty,showFind,setShowFind}){return <section><h1>Search</h1><p className="muted">LineFind-style project search with line numbers, highlighted matches and an integrated file viewer/editor.</p><div className="search"><input value={q}onChange={e=>setQ(e.target.value)}onKeyDown={e=>e.key==='Enter'&&search()}placeholder="Find text"/><button onClick={search}>🔎 Search</button></div><div className="list">{res.map((r,i)=><button key={r.path+'-'+r.line+'-'+i}onClick={()=>open(p.files.find(f=>f.path===r.path),true)}><b>{r.path} · Line {r.line}</b><code>{highlight(r.text,q)}</code></button>)}</div>{searchView&&<SearchFileView data={searchView}setSearchView={setSearchView}setSel={setSel}setText={setText}setDirty={setDirty}showFind={showFind}setShowFind={setShowFind}/>}</section>}
function SearchFileView({data,setSearchView,setSel,setText,setDirty,showFind,setShowFind}){const{file,query}=data,lines=file.content.split(/\r?\n/),matches=[];lines.forEach((l,i)=>{let re=new RegExp(esc(query),'ig');while(re.exec(l))matches.push({line:i})});const[active,setActive]=useState(0),[rendered,setRendered]=useState(file.ext==='.md'),refs=useRef([]);useEffect(()=>setActive(0),[file.path,query]);useEffect(()=>{if(!rendered)refs.current[matches[active]?.line]?.scrollIntoView({behavior:'smooth',block:'center'})},[active,rendered]);const next=()=>matches.length&&setActive((active+1)%matches.length),prev=()=>matches.length&&setActive((active-1+matches.length)%matches.length);function edit(){setSel(file);setText(file.content);setDirty(false);setSearchView(null);setShowFind(true);setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),0)}return <div className="searched-file"><div className="file-toolbar"><div><b>📄 {file.path}</b><small>{file.ext==='.md'?'Markdown Viewer + Editor':'Search result viewer'}</small></div><div className="toolbar-actions"><button onClick={edit}>✏️ Editor</button><button onClick={()=>cp(file.content)}>📋 Copy</button><button onClick={()=>dl(file.name,file.content)}>⬇ Download</button><button onClick={()=>{edit();setShowFind(true)}}>🔎 Find Text</button>{file.ext==='.md'&&<button onClick={()=>setRendered(!rendered)}>{rendered?'Raw':'Rendered'}</button>}</div></div>{file.ext==='.md'&&rendered?<div className="markdown-view"dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(marked.parse(file.content))}}/>:<div className="highlight-view">{lines.map((l,i)=><div key={i}ref={el=>refs.current[i]=el}className={matches[active]?.line===i?'active-line':''}><span>{i+1}</span><code>{highlight(l,query)}</code></div>)}</div>}{matches.length>0&&<div className="match-controller"><button onClick={prev}>◀ Previous</button><strong>{active+1}/{matches.length}</strong><button onClick={next}>Next ▶</button></div>}<div className="search-editor-note">Use <b>Editor</b> above to edit this file. The main Editor tab remains unchanged.</div></div>}
function Editor({sel,text,setText,dirty,save,showFind,setShowFind}){const[find,setFind]=useState(''),[rep,setRep]=useState(''),findRef=useRef();if(!sel)return <section><h1>Editor</h1><p>Select a file from Explorer or Search.</p></section>;function replaceOne(){if(!find)return;let i=text.indexOf(find);if(i>=0)setText(text.slice(0,i)+rep+text.slice(i+find.length))}function replaceAll(){if(!find)return;setText(text.split(find).join(rep))}return <section><div className="head"><div><h1>{sel.path} {dirty&&<em>● modified</em>}</h1><small>Local editor with Find, Replace and Replace All.</small></div><div className="toolbar-actions"><button onClick={()=>{setShowFind(true);setTimeout(()=>findRef.current?.focus(),0)}}>🔎 Find Text</button><button onClick={()=>cp(text)}>📋 Copy</button><button onClick={()=>dl(sel.name,text)}>⬇ Download</button><button onClick={save}disabled={!dirty}>💾 Save</button></div></div>{showFind&&<div className="replace"><input ref={findRef}value={find}onChange={e=>setFind(e.target.value)}placeholder="Find"/><input value={rep}onChange={e=>setRep(e.target.value)}placeholder="Replace with"/><button onClick={replaceOne}>Replace</button><button onClick={replaceAll}>Replace All</button></div>}<div className="editor"><pre>{text.split(/\r?\n/).map((_,i)=><div key={i}>{i+1}</div>)}</pre><textarea spellCheck="false"value={text}onChange={e=>setText(e.target.value)}/></div></section>}
function Tools({tool,setTool,input,setInput,regex,setRegex,regexText,setRegexText,output,run,clear}){const defs={text:['🧹','Text Cleanup','Paste messy text → remove extra spaces and blank lines.'],json:['{}','JSON Formatter','Paste JSON → Run → get readable formatted JSON.'],base64:['🔐','Base64','Paste text → Run → encode it to Base64.'],regex:['🔎','Regex','Enter a pattern + test text → Run → inspect matches and line numbers.'],jwt:['🎫','JWT Decoder','Paste a JWT → Run → decode its payload.'],uuid:['🆔','UUID','Select UUID → Run → generate a new UUID.'],timestamp:['⏱️','Timestamp','Enter Unix seconds or leave empty → Run.']};let ts=Object.keys(defs);return <section><div className="head"><div><h1>Developer Tools Hub</h1><p>Small developer utilities in one place.</p></div><button onClick={clear}>🧹 Clear</button></div><div className="tool-examples"><div className="tool-example-title">💡 Quick examples</div><div className="tool-example-grid">{ts.map(x=><button key={x}className={tool===x?'selected':''}onClick={()=>setTool(x)}><span className="example-icon">{defs[x][0]}</span><b>{defs[x][1]}</b><small>{defs[x][2]}</small></button>)}</div></div><div className="tabs">{ts.map(x=><button key={x}className={tool===x?'active':''}onClick={()=>setTool(x)}>{defs[x][0]} {defs[x][1]}</button>)}</div>{tool==='regex'?<div className="tool-grid"><div><label>Regular Expression</label><input value={regex}onChange={e=>setRegex(e.target.value)}placeholder="\\b[A-Z][a-z]+\\b"/><label>Test Text</label><textarea value={regexText}onChange={e=>setRegexText(e.target.value)}placeholder={'Hello RepoMind.\nThis Tool Finds Words.'}/></div><div><label>Output</label><textarea value={output}readOnly placeholder="Matches and results"/></div></div>:<><textarea value={input}onChange={e=>setInput(e.target.value)}placeholder={defs[tool][2]}/><textarea value={output}readOnly placeholder="Output"/></>}<div className="run-row"><button className="run-button"onClick={run}>▶ Run {defs[tool][1]}</button></div></section>}
function Diff({p,diff,setDiff}){const[a,setA]=useState(''),[b,setB]=useState('');async function go(){let f=p?.files.find(x=>x.path===a),g=p?.files.find(x=>x.path===b);if(!f||!g)return;setDiff({a,b,x:await read(f),y:await read(g)})}return <section><h1>Diff & Compare</h1><div className="search"><select onChange={e=>setA(e.target.value)}><option>Select first</option>{p?.files.filter(f=>f.text).map(f=><option key={f.path}>{f.path}</option>)}</select><select onChange={e=>setB(e.target.value)}><option>Select second</option>{p?.files.filter(f=>f.text).map(f=><option key={f.path}>{f.path}</option>)}</select><button onClick={go}>Compare</button></div>{diff&&<div className="diff"><pre>{diff.x}</pre><pre>{diff.y}</pre></div>}</section>}
function Transform({p,combine,compiled,setCompiled,split,setSplit,parts,dosplit}){return <section><h1>Transform</h1><div className="panel"><button onClick={combine}>Combine all text files</button><textarea value={compiled}onChange={e=>setCompiled(e.target.value)}/><button onClick={()=>dl('compiled_output.txt',compiled)}>Download</button></div><div className="panel"><h2>Reverse Split</h2><textarea value={split}onChange={e=>setSplit(e.target.value)}/><button onClick={dosplit}>Split</button>{parts.map(x=><p key={x.name}><b>{x.name}</b></p>)}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);